site_name: Navigating ML
theme: material
pages:
    - Main: index.md
    - Prequisites:
      - 'Python': 'myprereqs.md'

google_analytics: ['UA-86308542-1', 'https://michhar.github.io/navigating-ml/']
